### PR TITLE
Change revokation to revocation.

### PR DESCRIPTION
**Pull request by jbot-the-dev**
## Pull request summary

"Revokation" is a typo and does not match the message type "revocation" that Twitch uses. I do not have the means to test this at the moment, though I have implemented this fix successfully in a modified version of this library. I don't see reference to this in the documentation, so I don't think that needs updated. There are other uses of "revokation", though fixing them would fall into the category of a breaking change, so I left them alone for now.

Reference: https://dev.twitch.tv/docs/eventsub/handling-webhook-events

## Checklist

- [ ] If code changes were made then they have been tested.
    - [ ] I have updated the documentation to reflect the changes.
    - [x] I have updated the changelog with a quick recap of my changes.
- [x] This PR fixes an issue.
- [ ] This PR adds something new (e.g. new method or parameters).
- [ ] This PR is a breaking change (e.g. methods or parameters removed/renamed)
- [ ] This PR is **not** a code change (e.g. documentation, README, ...)

### CODE REVIEW

**Comment by chillymosh** [comment]
Technically this doesn't fix an issue, it would also now cause inconsistencies in the eventsub module as the event that is dispatched is also called revokcation as well as the model.

**Comment by jbot-the-dev** [comment]
In it's current state, "eventsub_revokation" will never be run, because message type "revokation" does not exist. I have personally run into this issue when debugging. Please look at my reference under "Twitch-Eventsub-Message-Type".

**Comment by chillymosh** [comment]
Ah I didn't read that properly, thanks.

**Comment by jbot-the-dev** [comment]
It looks like GitHub had auto-filled some details from the other pull request I was working on. I separated the two because they address separate issues. I have fixed the summary now.

**Comment by EvieePy** [comment]
Thanks 👍

**Pull request merged**
