### PR TITLE
Create Eventsub-specific CustomReward model

### LINKED ISSUE #254: CustomReward _init_ not compatible with EventSub data
rewards.py lines 71-74 try to get a broadcaster_id or channel_id from the data object that is passed in.
However, the reward data sent from twitch contains only 4 fields: Id, Title, Cost, and Prompt. 

As such, the creation of the CustomReward in /eventsub/models.py line 437 breaks any method attempting to use that data.

### PR DESCRIPTION
**Pull request by Roadcrosser**
## Pull request summary

Creates an Eventsub-specific model for Custom Channel Point rewards.

Fixes #254

## Checklist
- [x] If code changes were made then they have been tested.
    - [x] I have updated the documentation to reflect the changes.
    - [ ] I have updated the changelog with a quick recap of my changes.
- [x] This PR fixes an issue.
- [ ] This PR adds something new (e.g. new method or parameters).
- [ ] This PR is a breaking change (e.g. methods or parameters removed/renamed)
- [ ] This PR is **not** a code change (e.g. documentation, README, ...)

### CODE REVIEW

**Comment by Roadcrosser** [comment]
Will test soon and update docs appropriately.

**Comment by Roadcrosser** [comment]
As it turns out I will be unable to test the Channel Point Reward Add/Update/Remove endpoints so any assistance with that will be appreciated.

**Comment by IAmTomahawkx** [comment]
This appears to be missing typings

**Comment by kamalmostafa** [comment]
Confirming that this pull request works great for me, fixing #254 and enabling CustomReward handing in my bot.  Thanks VERY much!

**Comment by IAmTomahawkx** [comment]
Thanks for the pr!

**Pull request merged**
