### PR TITLE
Add user_id property to client

### PR DESCRIPTION
**Pull request by tkdrob**
## Pull request summary

Exposes the `user_id` associated with the token. This is useful as a unique identifier in applications where we only want a single instance configurable by the user.

## Checklist

- [x] If code changes were made then they have been tested.
    - [ ] I have updated the documentation to reflect the changes.
    - [x] I have updated the changelog with a quick recap of my changes.
- [ ] This PR fixes an issue.
- [x] This PR adds something new (e.g. new method or parameters).
- [ ] This PR is a breaking change (e.g. methods or parameters removed/renamed)
- [ ] This PR is **not** a code change (e.g. documentation, README, ...)

### CODE REVIEW

**Review by IAmTomahawkx — CHANGES_REQUESTED** [review]
Missing changelog and documentation updates, otherwise looks good

**Comment by tkdrob** [comment]
> Missing changelog and documentation updates, otherwise looks good

Sure, no problem. I do have other PRs I want to propose before a version bump. So I will update changelog without a version heading for now.

**Comment by IAmTomahawkx** [comment]
You can just leave the header as Master, Development etc

**Comment by tkdrob** [comment]
> You can just leave the header as Master, Development etc

I don't see `nick` referenced in the docs except for the examples so I'm not sure of `user_id` should be disclosed anywhere else.

**Pull request merged**
