### PR TITLE
Fix incorrect User.view_count type

### PR DESCRIPTION
**Pull request by tkdrob**
## Pull request summary
`View_count` has incorrect type, tuple. This fixes it, `int`

## Checklist

- [x] If code changes were made then they have been tested.
    - [ ] I have updated the documentation to reflect the changes.
    - [x] I have updated the changelog with a quick recap of my changes.
- [ ] This PR fixes an issue.
- [ ] This PR adds something new (e.g. new method or parameters).
- [x] This PR is a breaking change (e.g. methods or parameters removed/renamed)
- [ ] This PR is **not** a code change (e.g. documentation, README, ...)

### CODE REVIEW

**Comment by IAmTomahawkx** [comment]
This is actually a breaking change, and as such can't be introduced into twitchio v2. This may be more appropriate on the v3 branch once http models are fully introduced

**Comment by tkdrob** [comment]
How close is v2 to being release? I'm working on some other nonbreaking changes so this package can support twitch integration in https://github.com/home-assistant/core

**Comment by IAmTomahawkx** [comment]
V2 has been released for over a year

**Comment by chillymosh** [comment]
For info purposes.
This payload for view_count is being deprecated and eventually removed completely by Twitch.
https://discuss.dev.twitch.tv/t/get-users-api-endpoint-view-count-deprecation/37777

**Pull request closed without merging**
