### PR TITLE
Added old Pubsub format with try except

### PR DESCRIPTION
**Pull request by RobertErobert**
In #215 i accidently kicked out the old pubsub format.
Now both are supported.

### CODE REVIEW

**Comment by IAmTomahawkx** [comment]
have these changes been tested?

**Review by charlesmadere — CHANGES_REQUESTED** [review]
IMO the code in this PR is incorrectly written, and should look like this instead:

```python
    def __init__(self, http: "TwitchHTTP", obj: dict, channel: "PartialUser"):
        self._http = http
        self._channel = channel

        if "broadcaster_id" in obj:
            self._broadcaster_id = obj["broadcaster_id"]
        else:
            self._broadcaster_id = obj["channel_id"]

        self.id = obj["id"]
        self.image = obj["image"]["url_1x"] if obj["image"] else obj["default_image"]["url_1x"]
        self.background_color = obj["background_color"]
        self.enabled = obj["is_enabled"]
        self.cost = obj["cost"]
        self.title = obj["title"]
        self.prompt = obj["prompt"]
        self.input_required = obj["is_user_input_required"]

        if "max_per_stream_setting" in obj:
            self.max_per_stream = (
                obj["max_per_stream_setting"]["is_enabled"],
                obj["max_per_stream_setting"]["max_per_stream"],
            )
        else:
            self.max_per_stream = (
                obj["max_per_stream"]["is_enabled"],
                obj["max_per_stream"]["max_per_stream"],
            )

        if "max_per_user_per_stream_setting" in obj:
            self.max_per_user_stream = (
                obj["max_per_user_per_stream_setting"]["is_enabled"],
                obj["max_per_user_per_stream_setting"]["max_per_user_per_stream"],
            )
        else:
            self.max_per_user_stream = (
                obj["max_per_user_per_stream"]["is_enabled"],
                obj["max_per_user_per_stream"]["max_per_user_per_stream"],
            )

        if "global_cooldown_setting" in obj:
            self.cooldown = (
                obj["global_cooldown_setting"]["is_enabled"],
                obj["global_cooldown_setting"]["global_cooldown_seconds"],
            )
        else:
            self.cooldown = (
                obj["global_cooldown"]["is_enabled"],
                obj["global_cooldown"]["global_cooldown_seconds"],
            )

        self.paused = obj["is_paused"]
        self.in_stock = obj["is_in_stock"]
        self.redemptions_skip_queue = obj["should_redemptions_skip_request_queue"]
        self.redemptions_current_stream = obj["redemptions_redeemed_current_stream"]
        self.cooldown_until = obj["cooldown_expires_at"]
```

As this PR is right now, there is an either-or approach with entire sets of JSON keys. For example, a case is not supported where `max_per_stream_setting` does not exist in the JSON, but `max_per_user_per_stream_setting` does.

However, my approach is rather verbose, maybe there are better/prettier ways to implement.

**Comment by chillymosh** [comment]
Could possibly look into writing a parser of some sort if we aren't sure if some keys may not always be received?

**Review by L33Tech — APPROVED** [review]
Approved with charlesmadere's changes

**Review by IAmTomahawkx — APPROVED** [review]

**Comment by charlesmadere** [comment]
This PR was merged in but does not contain any of the changes requested in [this comment](https://github.com/TwitchIO/TwitchIO/pull/232#pullrequestreview-793951371). So I've now opened a new PR (#243) that fixes those issues.

**Pull request merged**
