### PR TITLE
Pyproject toml

### PR DESCRIPTION
**Pull request by joelsgp**
## Pull request summary

This replaces setup.py with pyproject.toml this is needed because setup.py is deprecated

Another advantage is this lets us embed the 120 character line limit in the settings, so Black will use it automatically

## Checklist

- [ ] If code changes were made then they have been tested.
    - [ ] I have updated the documentation to reflect the changes.
    - [ ] I have updated the changelog with a quick recap of my changes.
- [ ] This PR fixes an issue.
- [ ] This PR adds something new (e.g. new method or parameters).
- [ ] This PR is a breaking change (e.g. methods or parameters removed/renamed)
- [x] This PR is **not** a code change (e.g. documentation, README, ...)

### CODE REVIEW

**Comment by IAmTomahawkx** [comment]
Hi there, thanks for the PR but we're not looking to migrate to pyproject.toml at this time

**Comment by IAmTomahawkx** [comment]
It should be noted that our `3.0` branch does make use of pyproject.toml, however the setup.py file is not entirely deprecated. Invoking the file directly is indeed deprecated, however the setup.py file is still fine by itself

**Comment by joelsgp** [comment]
Ah I should have checked 3.0 thanks, didn't realise that was the working branch

**Comment by joelsgp** [comment]
I think using pipenv would be quite good for managing the dependencies and extras, you can use `pipenv requirements > requirements.txt` to make the requirements.txt off it too

**Pull request closed without merging**
