### PR TITLE
fix a forgotten nonce

### PR DESCRIPTION
**Pull request by dzmuh97**
## Pull request summary

After we subscribe to topics we wait for the `event_pubsub_nonce`, but it is not called because the server does not pass the nonce it should return in response to the client, which we wait for in `websocket.py:200`

## Checklist

- [x] If code changes were made then they have been tested.
    - [ ] I have updated the documentation to reflect the changes.
    - [x] I have updated the changelog with a quick recap of my changes.
- [x] This PR fixes an issue.
- [ ] This PR adds something new (e.g. new method or parameters).
- [ ] This PR is a breaking change (e.g. methods or parameters removed/renamed)
- [ ] This PR is **not** a code change (e.g. documentation, README, ...)

### CODE REVIEW

**Comment by chillymosh** [comment]
This is most likely because the nonce is optional here.

**Review by IAmTomahawkx — CHANGES_REQUESTED** [review]
hello, this PR is currently failing black (linting), and has not had a changelog entry added.
Please run black on the library and add a changelog entry to docs/changelog.rst.

The change itself looks fine though

**Comment by chillymosh** [comment]
@dzmuh97 could you please complete the PR request

**Review by IAmTomahawkx — APPROVED** [review]
LGTM

**Pull request merged**
