### PR TITLE
Remove dependency on typing_extensions

### PR DESCRIPTION
**Pull request by joelsgp**
## Pull request summary

`Literal` is now in the standard library. Also remove the old annotations imports, as the relevant python versions are no longer supported.

## Checklist

- [ ] If code changes were made then they have been tested.
    - [ ] I have updated the documentation to reflect the changes.
    - [ ] I have updated the changelog with a quick recap of my changes.
- [ ] This PR fixes an issue.
- [ ] This PR adds something new (e.g. new method or parameters).
- [ ] This PR is a breaking change (e.g. methods or parameters removed/renamed)
- [ ] This PR is **not** a code change (e.g. documentation, README, ...)

### CODE REVIEW

**Comment by IAmTomahawkx** [comment]
If you have further PRs to make, i would suggest joining our discord, which is linked in the README

**Comment by joelsgp** [comment]
3.7 is about to go end-of-life https://devguide.python.org/versions/

I'm already in the discord but  I should have checked the docs section on this before submitting. I was mistaken on the future imports, I thought that was already mandatory but it's tbd https://devguide.python.org/versions/

**Comment by chillymosh** [comment]
Python 2.7 is also EoL but people still use it and rely on it in companies :)

**Comment by joelsgp** [comment]
> Python 2.7 is also EoL but people still use it and rely on it in companies :)

I'm sorry to hear that, I will pray for them 🙏

**Comment by IAmTomahawkx** [comment]
our support is not based around the timing the python org provides for lifecycles. We will provide support for 3.7+ for the lifetime of this semver cycle (V2). We will drop support for older python versions in our next cycle (V3)

**Comment by joelsgp** [comment]
Understood, and I'd appreciate it if the semantic versioning / version branch model was explained in https://github.com/TwitchIO/TwitchIO#contributing for future reference

**Pull request closed without merging**
