### PR TITLE
Fix `TypeError: 'NoneType' object is not subscriptable`

### PR DESCRIPTION
**Pull request by Bluscream**
```
****** MESSAGE_RE Failed! ******
Traceback (most recent call last):
  File "/home/blu/.local/lib/python3.11/site-packages/twitchio/websocket.py", line 317, in _process_data
    if parsed["action"] == "PING":
       ~~~~~~^^^^^^^^^^
TypeError: 'NoneType' object is not subscriptable
```

## Checklist

- [x] If code changes were made then they have been tested.
    - [ ] I have updated the documentation to reflect the changes.
    - [ ] I have updated the changelog with a quick recap of my changes.
- [x] This PR fixes an issue.
- [ ] This PR adds something new (e.g. new method or parameters).
- [ ] This PR is a breaking change (e.g. methods or parameters removed/renamed)
- [ ] This PR is **not** a code change (e.g. documentation, README, ...)

### CODE REVIEW

**Comment by chillymosh** [comment]
1. What was the data being received that was failed to be parsed?
2. Is this simply a case of you not handing message.echo?

**Comment by Bluscream** [comment]
> What was the data being received that was failed to be parsed?

It didn't show any extra data except the one shown in the stacktrace

> Is this simply a case of you not handing message.echo?

message.echo is handled as per your example

> We simply need some more information as this may not be an issue or it may be something elsewhere that needs fixing, 

I can only give as much info as you're asking and asmuch as i see in the console

> What was happening when this error happened?

regular usage, nothing special

> What is your codebase?

sorry can't share that because of licensing issues

**Comment by chillymosh** [comment]
@deseipel please be more specific as part of the Twitch IRC spec requires newlines

**Comment by deseipel** [comment]
the bot i have posts answers from GPT3 OR ChatGPT to Twitch.  ask openai to write a poem or haiku and you'll get the bug.

**Comment by chillymosh** [comment]
@deseipel you still haven't answered my question from Jan.
I'm also not going to setup a connection to a 3rd party service which has no relevance to the libs internals.

**Comment by deseipel** [comment]
Interesting, thank you for finding root cause.  this came up during my own testing when I was copy/pasting test messages.  makes sense now.  I appreciate it.

**Pull request closed without merging**
